env:
  browser: true
  es6: true
  jquery: true
extends:
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
rules:
  {
    no-unused-vars: 0,
    no-use-before-define: 0,
    semi: [2, 'never'],
    'react/jsx-filename-extension': [1, { 'extensions': ['.js', '.jsx'] }],
    'react/prop-types': 0,
    operator-linebreak: [error, "after"]
  }
